### ISSUE TITLE
Add Cross-Platform support in PyTest Pre-Commit Hook

### ISSUE THREAD

**Issue by aditeyabaral** [HackerSpace-PESU/pesu-auth#29]
The current pre-commit hook for `pytest` comprises the following:

```yaml
- repo: local
  hooks:
    - id: pytest
      name: Run Pytest
      entry: bash -c '...'
      language: system
      types: [ python ]
      pass_filenames: false

```
Specifically, the hook runs the following `bash` snippet. The logic is quite self-explanatory. It loads a `.env` if present, and if it has access to user credentials, it runs the full set of tests. Otherwise, it runs the tests that do not need authentication.

```bash
if [[ -f .env ]]; then
    set -a
    source .env
    set +a
fi

if [[ -z "$TEST_PRN" || -z "$TEST_PASSWORD" ]]; then
    echo "Secrets missing. Running only tests not requiring secrets..."
    pytest -m "not secret_required" --disable-warnings -v -s
else
    echo "Running all tests..."
    pytest --cov=app --cov-report=term-missing --cov-fail-under=80 --disable-warnings -v -s
fi

```
However, it's obvious that this script will not work on a Windows machine. The current hook uses a Bash one-liner that relies on POSIX shell syntax (`[[`, `source`, etc.), which is not available in default Windows shells (CMD, PowerShell). We should enable developers on Windows machines (let's not be judgmental) to also run the pre-commit hooks and test their build locally before pushing their commits. My bad for forgetting you all when I first built this, sorry bros :(

## Proposed Fix

We should mitigate this by moving the entire pytest logic (loading `.env` + running tests + returning error code) to a Python script that invokes the `subprocess` module's corresponding commands, and invoking the script in the hook config, like this:

```yaml
- repo: local
  hooks:
    - id: pytest
      name: Run Pytest
      entry: python scripts/run_tests.py
      language: system
      types: [ python ]
      pass_filenames: false
```
This is a rough pseudo-code/implementation of the requirement:
```python
load_dotenv()

if os.getenv("TEST_PRN") and os.getenv("TEST_PASSWORD"):
    command = # cmd to run full set of tests
else:
   command = # cmd to run reduced set of tests
res = subprocess.run(command)
sys.exit(res.code)
```

Easy fix, but I am open to discussions on cleaner solutions.
